import type { SourceConfig } from './types';

export const API_RSS_SOURCES: SourceConfig[] = [
  {
    name: '量子位',
    url: 'https://www.qbitai.com/feed',
    priority: 1,
    authorityLevel: 'headMedia',
    tier: 'P0',
    status: 'active',
    rationale: '中文 AI 垂直媒体，模型、产品、产业动态密度高。',
  },
  {
    name: '机器之心',
    url: 'https://www.jiqizhixin.com/rss',
    priority: 0.98,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '中文 AI 技术媒体，适合补技术与论文向新闻。',
  },
  {
    name: '新智元',
    url: 'https://www.aixinzhi.com/rss',
    priority: 0.96,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '中文 AI 产业媒体，适合补行业落地和商业动态。',
  },
  {
    name: 'InfoQ',
    url: 'https://www.infoq.cn/feed',
    priority: 0.95,
    authorityLevel: 'headMedia',
    tier: 'P0',
    status: 'active',
    rationale: '技术与工程化质量稳定，适合补开发者和平台能力类新闻。',
  },
  {
    name: 'RadarAI',
    url: 'https://radarai.top/feed.xml',
    priority: 0.94,
    authorityLevel: 'headMedia',
    tier: 'P0',
    status: 'active',
    rationale: 'AI 聚合站，更新快，适合补热点和开源动态。',
  },
  {
    name: '雷锋网AI',
    url: 'https://www.leiphone.com/feed/categoryRss/name/aijuejinzhi',
    priority: 0.94,
    authorityLevel: 'headMedia',
    tier: 'P0',
    status: 'active',
    rationale: '中文 AI 垂直媒体，适合补产业、产品与公司新闻。',
  },
  {
    name: '36Kr',
    url: 'https://36kr.com/feed',
    priority: 0.9,
    authorityLevel: 'generalMedia',
    tier: 'P1',
    status: 'active',
    rationale: '泛科技媒体，适合补创业、融资和商业化相关新闻。',
  },
  {
    name: '钛媒体',
    url: 'https://www.tmtpost.com/rss',
    priority: 0.88,
    authorityLevel: 'generalMedia',
    tier: 'P1',
    status: 'active',
    rationale: '泛科技和商业媒体，适合补行业趋势和公司动态。',
  },
  {
    name: '少数派',
    url: 'https://sspai.com/feed',
    priority: 0.82,
    authorityLevel: 'generalMedia',
    tier: 'P1',
    status: 'active',
    rationale: '产品体验与工具应用内容较多，适合补 AI 产品实践。',
  },
  {
    name: 'IT之家',
    url: 'https://www.ithome.com/rss',
    priority: 0.9,
    authorityLevel: 'generalMedia',
    tier: 'P1',
    status: 'active',
    rationale: '更新频率高，适合补大厂、终端、产品快讯。',
  },
  {
    name: '爱范儿',
    url: 'https://www.ifanr.com/feed',
    priority: 0.86,
    authorityLevel: 'generalMedia',
    tier: 'P1',
    status: 'active',
    rationale: '消费科技与产品应用向内容较多，适合补 AI 产品落地。',
  },
  {
    name: 'OpenAI News',
    url: 'https://openai.com/news/rss.xml',
    priority: 1,
    authorityLevel: 'official',
    tier: 'P0',
    status: 'active',
    rationale: '官方一手动态，适合补模型、产品、开放平台发布。',
  },
  {
    name: 'DeepMind Blog',
    url: 'https://deepmind.google/blog/rss.xml',
    priority: 0.99,
    authorityLevel: 'official',
    tier: 'P0',
    status: 'active',
    rationale: 'Google DeepMind 官方动态，适合补研究和模型发布。',
  },
  {
    name: 'Google AI Blog',
    url: 'https://blog.google/innovation-and-ai/technology/ai/rss/',
    priority: 0.97,
    authorityLevel: 'official',
    tier: 'P0',
    status: 'active',
    rationale: 'Google AI 官方博客，适合补 Gemini、产品和平台能力。',
  },
  {
    name: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog/feed.xml',
    priority: 0.96,
    authorityLevel: 'official',
    tier: 'P0',
    status: 'active',
    rationale: '开源生态核心来源，适合补模型、工具链和社区热点。',
  },
  {
    name: 'Berkeley BAIR',
    url: 'https://bair.berkeley.edu/blog/feed.xml',
    priority: 0.94,
    authorityLevel: 'official',
    tier: 'P1',
    status: 'active',
    rationale: '顶级研究机构博客，适合补研究方向和学术动态。',
  },
  {
    name: 'MIT Tech Review',
    url: 'https://www.technologyreview.com/feed/',
    priority: 0.92,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '国际科技媒体，适合补 AI 趋势、政策和产业分析。',
  },
  {
    name: 'TechCrunch AI',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    priority: 0.91,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '创业和产品发布信号强，适合补国际 AI 商业动态。',
  },
  {
    name: 'VentureBeat AI',
    url: 'https://venturebeat.com/category/ai/feed/',
    priority: 0.9,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '国际 AI 媒体，适合补企业级 AI、产品和商业新闻。',
  },
  {
    name: 'Ars Technica AI',
    url: 'https://arstechnica.com/ai/feed/',
    priority: 0.88,
    authorityLevel: 'headMedia',
    tier: 'P1',
    status: 'active',
    rationale: '国际科技媒体，适合补 AI 政策、安全与产品新闻。',
  },
  {
    name: 'Hacker News AI',
    url: 'https://hnrss.org/frontpage?q=AI',
    priority: 0.78,
    authorityLevel: 'generalMedia',
    tier: 'P2',
    status: 'active',
    rationale: '社区热帖聚合，适合补开源项目和开发者侧热点。',
  },
];

export const ACTIVE_API_RSS_SOURCES = API_RSS_SOURCES.filter(
  (source) => source.status === 'active' && source.enabled !== false,
);

export const API_RSS_SOURCE_MAP = new Map(ACTIVE_API_RSS_SOURCES.map((source) => [source.name, source]));
